apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-login-deployment
  labels:
    app: php-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-login
  template:
    metadata:
      labels:
        app: php-login
    spec:
      containers:
      - name: php-login-container
        image: anonymousewashere/my-php-login:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-login-service
spec:
  selector:
    app: php-login
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31110
