apiVersion: v1
kind: Service
metadata:
  name: php-login-service
  namespace: default
spec:
  selector:
    app: php-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31110
  type: NodePort